version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27019:27017"
  api:
    container_name: api-container
    image: node:12
    working_dir: /usr/app/clean-node-api
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    volumes:
      - ./dist:/usr/app/clean-node-api/dist
      - ./package.json:/usr/app/clean-node-api/package.json
    ports:
      - "7777:7777"
      - "9222:9222"
    links:
      - mongo